index<~key~>Главная страница
about<~key~>О нас
arrays<~key~>Массивы
sdwig_array<~page~>Сдвиг массива
based<~key~>Базовые алгоритмы
swap<~page~>Обмен двух переменных значениями
bin_find<~page~>Бинарный поиск по ответу
dividers<~page~>Разбиение на простые множители
reverse<~page~>Реверс массива
split_to_digits<~page~>Разбиение числа на цифры
integer<~key~>Алгоритмы обработки чисел
stack<~page~>Стек
struct<~key~>Структуры данных
dict<~page~>Ассоциативный массив
deletement<~page~>Удаление элемента из массива
